name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install SDL2 library
    - name: Install SDL2
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

    # Build the project
    - name: Build
      run: cargo build --verbose

    # Run tests
    - name: Run tests
      run: cargo test --verbose
